=== jackmoxley/Moxy-Parser/moxy-parent/moxy-realizer/src/main/java/com/jackmoxley/moxy/realizer/xml/Realizer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.jackmoxley.com/Moxy" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:moxy="http://www.jackmoxley.com/Moxy">

    <element name="beans" type="moxy:Beans"></element>
    
    <complexType name="Bean">
    	<sequence>
    		<element name="constructor" type="moxy:BeanConstructor"
    			maxOccurs="1" minOccurs="0" />
    		<element name="field" type="moxy:BeanField"
    			maxOccurs="unbounded" minOccurs="0" />
    		<element name="method" type="moxy:BeanMethod"
    			maxOccurs="unbounded" minOccurs="0" />
    	</sequence>
    	<attribute name="name" type="string" use="required" />
    	<attribute name="class" type="string" use="optional" />
    	<attribute name="extends" type="string" use="optional" />
    	<attribute name="includes" type="string" use="optional" />
    	<attribute name="singleton" type="boolean" default="false" use="optional"></attribute>
    </complexType>

    <complexType name="BeanConstructor">
    	<complexContent>
    		<extension base="moxy:HasArguments">
    		</extension>
    	</complexContent>
    </complexType>
    
    
    <complexType name="HasArguments" abstract="true">
    	<sequence>
    		<element name="argument" type="moxy:BeanArgument"
    			maxOccurs="unbounded" minOccurs="0"/>
    	</sequence>
    </complexType>
    
    <complexType name="BeanMethod">
    	<complexContent>
    		<extension base="moxy:HasArguments">
    			<attribute name="name" type="string" use="required"/>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="BeanArgument">
    	<sequence></sequence>
    	<attribute name="term" type="string" use="optional"/>
    	<attribute name="bean" type="string" use="optional"/>
    	<attribute name="value" type="string" use="optional"/>
    	<attribute name="transformer" type="string" use="optional"/>
    </complexType>
    
    <complexType name="BeanField">
    	<complexContent>
    		<extension base="moxy:BeanArgument">
    			<attribute name="name" type="string"  use="required"/>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="Beans">
    	<sequence>
    		<element name="bean" type="moxy:Bean" maxOccurs="unbounded" minOccurs="0"/>
    	</sequence>
    </complexType>

</schema>

=== jackmoxley/Moxy-Parser/moxy-parent/moxy-grammer/src/main/java/com/jackmoxley/moxy/grammer/bnf/BNFRuleRealizer.xml
<?xml version="1.0" encoding="UTF-8"?>
<moxy:beans xmlns:moxy="http://www.jackmoxley.com/Moxy"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.jackmoxley.com/Moxy ../../realizer/xml/Realizer.xsd ">
	
	
	<moxy:bean singleton="true" class="com.jackmoxley.moxy.grammer.RealizedRuledGrammer" name="rule">
		<moxy:field name="start" value="syntax"/> <!-- default -->
		<moxy:method name="put">
			<moxy:argument term="rule-name"/> 
			<moxy:argument bean="expression" term="expression"/> 
		</moxy:method>
		<moxy:method name="putSyntax">
			<moxy:argument term="rule-name"/> 
			<moxy:argument term=""/> 
		</moxy:method>
	</moxy:bean>

	<moxy:bean name="ruleList">
		<moxy:method name="add">
			<moxy:argument bean="list" term="list*"/>
		</moxy:method>
		<moxy:method name="add">
			<moxy:argument bean="expression" term="expression*" />
		</moxy:method>
		<moxy:method name="add">
			<moxy:argument bean="character" term="character*" />
		</moxy:method>
		<moxy:method name="add">
			<moxy:argument bean="text" term="text*" />
		</moxy:method>
		<moxy:method name="add">
			<moxy:argument bean="symbol" term="rule-name*" />
		</moxy:method>
	</moxy:bean>

	<moxy:bean name="expression" class="com.jackmoxley.moxy.rule.functional.OptionRule"
		extends="ruleList" />
		
	<moxy:bean name="list" class="com.jackmoxley.moxy.rule.functional.SequenceRule"
		extends="ruleList" />
		
	<moxy:bean name="character" class="com.jackmoxley.moxy.rule.terminating.CharacterRule">
		<moxy:constructor>
			<moxy:argument term="character"/>
		</moxy:constructor>
	</moxy:bean>
	
	<moxy:bean name="text" class="com.jackmoxley.moxy.rule.terminating.StringRule">
		<moxy:constructor>
			<moxy:argument term="text"/>
		</moxy:constructor>
	</moxy:bean>
	
	<moxy:bean name="symbol" class="com.jackmoxley.moxy.rule.functional.PointerRule">
		<moxy:constructor>
			<moxy:argument value="true" transformer="com.jackmoxley.moxy.realizer.transformer.BooleanTransformer"/>
			<moxy:argument term="rule-name"/>
		</moxy:constructor>
	</moxy:bean>

</moxy:beans>
